[workspace]

[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6"
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

